name: Manual deploy

on: [workflow_dispatch]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Install Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Build Jar
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gradle bootJar
        
      - name: Echo
        run: ll
        
      - name: Copy Jar
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "./app/lib/app.jar"
          target: "~/app"
  
