name: Manual deploy

on: [workflow_dispatch]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Install Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Build Jar
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gradle bootJar
        
      - name: Create Key File
        run: echo ${{ secrets.SKAARD_KEY }} > key.txt
       
      - name: Copy Jar to Server
        run: scp -i key.txt -P ${{ secrets.SKAARD_PORT }} ./app/build/libs/app.jar ${{ secrets.SKAARD_USER }}@${{ secrets.SKAARD_HOST }}:~/app 
  
